#!/usr/bin/env sh
# )A( - Andromeda Appificator 13.10.2
# startApp proxy launcher
# Luca Cappelletti (c) 2010-2013
# licensed under the terms of GNU/GPL
#
# take into account arguments
# do quote because it passes the LaunchPad parsing

## hardcoded debug mode
[ -z $DEBUG ] && DEBUG="No"
if tty -s
then
:
else

        if [ "$DEBUG" = "Yes" ]
        then

                xterm -e $0
                
        else
        :
        fi
        
fi

# check against Share service
if [ -h /home/FirefoxUX/Share ] && [ -e /home/FirefoxUX/Share ] && [ -d /tmp/Share ]
then
:
else
        # just remove and rebuild
        rm -rf --preserve-root /home/FirefoxUX/Share
        # add /tmp/Share root owner, valid only in first install
        #2>/dev/null ASAP after debug
        mkdir -p /tmp/Share 
        # world only read write not exec (anti malware)
        chmod -R 777 /tmp/Share

        ln -s /tmp/Share /home/FirefoxUX/Share
        wait
fi


# check against Volatile cache service
if [ -h /home/FirefoxUX/.cache/Volatile ] && [ -e /home/FirefoxUX/.cache/Volatile ]
then
:
else

        rm -rf --preserve-root /tmp/FirefoxUX 2>/dev/null
        rm -rf --preserve-root /home/FirefoxUX/.cache/Volatile 2>/dev/null
        mkdir -p /tmp/FirefoxUX 2>/dev/null
        chmod -R 700 /tmp/FirefoxUX 2>/dev/null
        ln -s /tmp/FirefoxUX /home/FirefoxUX/.cache/Volatile 2>/dev/null

fi

# try to start pulseaudio!!
if [ -x $(which start-pulseaudio-x11) ]
then

        start-pulseaudio-x11 &
        
else
:
fi


if [ "$#" -eq 0 ]
then

:

else

        arguments="$@"
        
fi

# d u nou sQr pshr?
if [ -x /home/FirefoxUX/.App/ioFirefoxUX28.0a1-Debian7/Linux-ia32/startApp ] || [ "$(mount | grep -w FirefoxUX)" != "" ]
then
:
else

# force umount also if not mounted
$(which sudo) $(which umount) -d -f -l /home/FirefoxUX/.App
wait

# mount over also if just mounted
$(which sudo) $(which mount) -t iso9660 -o loop,noatime,nodiratime,norelatime,exec,uid=FirefoxUX,gid=FirefoxUX /home/FirefoxUX/.App/FirefoxUX.app /home/FirefoxUX/.App
wait
fi

export PATH=/home/FirefoxUX:/home/FirefoxUX/bin:/home/FirefoxUX/.local/bin:/home/FirefoxUX/.App:/home/FirefoxUX/.App/bin:$PATH
export LD_LIBRARY_PATH=/home/FirefoxUX:/home/FirefoxUX/lib:/home/FirefoxUX/.local/lib:/home/FirefoxUX/.App:/home/FirefoxUX/.App/lib:$LD_LIBRARY_PATH

#dbus-launch --exit-with-session /home/FirefoxUX/.App/ioFirefoxUX28.0a1-Debian7/Linux-ia32/startApp $arguments

/home/FirefoxUX/.App/ioFirefoxUX28.0a1-Debian7/Linux-ia32/startApp $arguments

wait

killall -u FirefoxUX

exit 0
